### ISSUE TITLE
migrate redis to aws-elasticache (3/26)

### ISSUE THREAD

**Issue by ChrisMcGowan** [cloud-gov/cg-uaa-extras#172]
With k8s going away, this app needs to use the aws-elasticache service and will need the TLS changes made to support the new redis version

## Acceptance Criteria

- [ ] - Migrate the app in all three environments to use the new aws-elasticache service 

--- 

## Security considerations
n/a

## Implementation sketch

* [x] - Create new aws-elasticache redis accounts - done in all 3 environments as `redis-accounts-aws` 
* [x] - Update the app code to use the new service/TLS
* [x]  - Test

**Comment by karareinsel** [comment]
@ccostino @soutenniza to work on this week during downtime in support hours.

**Comment by ccostino** [comment]
PR is up! https://github.com/cloud-gov/cg-uaa-extras/pull/175

**Comment by ccostino** [comment]
There's a good amount of discussion in the PR on how to handle this update - to support this, I've added functionality to switch the app to a maintenance mode to ensure no requests can be made while services are unavailable.

**Comment by ccostino** [comment]
@apburnes had a great suggestion of creating a simple migrator app to migrate the existing data in the current Redis service for UAA extras that also listens for changes (using the [`monitor`](https://pypi.org/project/redis/#monitor) feature of the Python Redis library), then update `uaa-extras` itself to point to the new service.  Once we confirm things are working and flowing only to the new Redis instance, we can tear down the migration app and call it a day.

**Comment by ccostino** [comment]
PR for the migration app has been created! https://github.com/cloud-gov/cg-uaa-extras-redis-migrator/pull/1

**Comment by ccostino** [comment]
The migrator app with monitor is now ready to go; at this point, I think we're ready to make the update whenever we'd like.

**Comment by ccostino** [comment]
As @bengerman13 noted, our steps now are the following:

- Run the migrator app to migrate data from old Redis to new Redis and listen for anything new going in to automatically copy over
- Verify the migration worked
- Merge the updates in https://github.com/cloud-gov/cg-uaa-extras/pull/175
- Test that things work and verify that things are flowing to just new Redis
- Stop and delete the migrator app
- Delete old service instance

We should pause the production deployment of UAA extras when we do this, test these steps and verify everything one more time in staging, then do the same in production.

I'd like to be pairing with someone when doing this, so I'm placing this in blocked until we determine a day/time to do this.

**Comment by ccostino** [comment]
🎉 this is completely finished!  Thanks again for the help and pairing, @bengerman13!

- New Redis instances being used
- All old Redis instances across all environments have been removed
- Migrator app was deleted in all environments after being used
