### ISSUE TITLE
Reset password functionality not working properly

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-uaa-extras#176]
When a user goes through the password reset steps, they are advised to log in with a temporary password that is generated for them, and then to change that password after they successfully log in. When the user attempts to update their password using their temporary password, and a new password, an error occurs preventing them from updating their password.

<img width="508" alt="Screen Shot 2021-03-24 at 2 24 59 PM" src="https://user-images.githubusercontent.com/58419/112365630-41bc7500-8cae-11eb-9048-cf06a528a3d7.png">

**Comment by bengerman13** [comment]
@mheadd this looks like the stratos page, not uaa-extras. Is that right?

**Comment by mheadd** [comment]
Yup, that's correct. Was blanking on the proper place to capture this.

**Comment by mheadd** [comment]
https://github.com/cloud-gov/stratos does not have issues enabled

**Comment by spgreenberg** [comment]
While that screen shot may be stratos, the 500 error is related to uaa-extras.

**Comment by spgreenberg** [comment]
See: https://gsa-tts.slack.com/archives/G3JNU3HJL/p1616611794004900 for team discussion

**Comment by bengerman13** [comment]
We're talking about two different issues. The one with stratos (captured in the screenshot) should be put on this repo: https://github.com/cloud-gov/cg-deploy-stratos

I've also already reached out to the Stratos team about it, and there's not currently a workaround for it

**Comment by bengerman13** [comment]
@mheadd is this issue about not being able to reset passwords in Stratos, or about getting a 500 error when updating passwords in uaa-extras?

**Comment by spgreenberg** [comment]
The support request was related to uaa-extras.

**Comment by mheadd** [comment]
Closing in favor of: https://github.com/cloud-gov/cg-deploy-stratos/issues/36

We can open a new issue in this repo for the support request.
